### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by 15751064254** [lw-lin/CoolplaySpark#22]
您好 @lw-lin 
3.2 ReceiverSupervisor  [详解，图片无法显示。麻烦您修改下。](https://github.com/lw-lin/CoolplaySpark/blob/master/Spark%20Streaming%20%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E7%B3%BB%E5%88%97/3.2%20Receiver%2C%20ReceiverSupervisor%2C%20BlockGenerator%2C%20ReceivedBlockHandler%20%E8%AF%A6%E8%A7%A3.md#receiversupervisor-详解)

**Comment by lw-lin** [comment]
Closing this as this has been fixed via https://github.com/lw-lin/CoolplaySpark/commit/4c4d2fb33594b42e40f58cd9eee085c2ec1731a9.

Thank you @15751064254, @mtunique !

**Comment by lw-lin** [comment]
cc @wongxingjun about this
